name: "cdpvd_dashboards_store"
version: "0.0.0"
config-version: 2

profile: "replaceMeInLocals"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

seeds:
    ### WARN : !IMPORTANT : overriding must be redefined in the cssXX project, as dbt does not support config inheritance.
    # >>> BEGIN
    core_dashboards_store:
        +enabled: true
    ### <<< END
    cdpvd_dashboards_store:
        dashboards:
            other:
                pevr:
                    +tags: ["pevr"]
                    +schema: "dashboard_pevr"
models:
    ### WARN : !IMPORTANT : overriding must be redefined in the cssXX project, as dbt does not support config inheritance.
    # >>> BEGIN
    core_dashboards_store:
        +enabled: true # By default, all models in the core schould be enabled
        marts:
            human_resources:
                features:
                staging:
            educ_serv:
                features:
                staging:

        interfaces:
            gpi:
                i_gpm_e_dan:
                    +enabled: false
            jade:
                i_e_ri_mentions:
                    +enabled: false
                i_t_prog:
                    +enabled: false
    ### <<< END

    # This code block can be safely overriden in the cssXX_dashboards_store.
    # There is no need for code duplication here
    cdpvd_dashboards_store:
        +materialized: table
        dashboards:
            other:
                pevr:
                    +tags: ["pevr"]
                    +schema: "dashboard_pevr"
                    pbi_tables:
                        +post-hook:
                            - "{{ core_dashboards_store.stamp_model('dashboard_pevr') }}"
        interfaces:
            +materialized: ephemeral

vars:
    is_context_core: false
    # The source database to pull the data for a css.
    database_bi: "Replace me in the CSS repositery"
    database_paie: "Replace me in the CSS repositery"
    database_gpi: "Replace me in the CSS repositery"
    database_jade: "Replace me in the CSS repositery"
    database_prodrome: "Replace me in the CSS repositery" # Modelling output from the Sciance's models.

    interfaces:
        gpi:
            max_etapes: 30 # Must be set to the number of etapes, as found in gpm_t_obj_mat_grp
            max_periodes: 20 # Must be set to the number of periodes, as identified in gpm_t_cal
    marts:
        educ_serv:
            recency:
                years_of_data_absences: 10 # How many years of data to keep for the 'absences' centric dashboards.
                years_of_data_grades: 10 # How many years of data to keep for the 'grades' centric dashboards.
    dashboards:
        res_epreuves:
            cod_css: replaceme # The code of the CSS to use for the res_epreuves dashboard. A regex like placeholder. Something like '866%'
