version: 2

models:
  - name: stg_adresses_eleves
    description: >
      table showing students' residential addresses for each year.
    tests:
      - core_dashboards_store.resolution:
          combination_of_columns:
            - fiche
            - annee
